// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIUn33YJIrX_nnbJfE9e9rvS02wbD8xU',
    appId: '1:361691330793:web:7d2523039eefda030bd878',
    messagingSenderId: '361691330793',
    projectId: 'mentor-classes-erp',
    authDomain: 'mentor-classes-erp.firebaseapp.com',
    storageBucket: 'mentor-classes-erp.firebasestorage.app',
    measurementId: 'G-TW40VLGTEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEU0ZkDoHdDM6DiztkdavQNGNoIq2kJuA',
    appId: '1:361691330793:android:61f363071999d1750bd878',
    messagingSenderId: '361691330793',
    projectId: 'mentor-classes-erp',
    storageBucket: 'mentor-classes-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSwCC8DvFCk7ePYwXnpzz3wWb6AjWrSg',
    appId: '1:361691330793:ios:9c1078996783779b0bd878',
    messagingSenderId: '361691330793',
    projectId: 'mentor-classes-erp',
    storageBucket: 'mentor-classes-erp.firebasestorage.app',
    iosBundleId: 'com.harshit.mentorclasses.mentorClasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSwCC8DvFCk7ePYwXnpzz3wWb6AjWrSg',
    appId: '1:361691330793:ios:9c1078996783779b0bd878',
    messagingSenderId: '361691330793',
    projectId: 'mentor-classes-erp',
    storageBucket: 'mentor-classes-erp.firebasestorage.app',
    iosBundleId: 'com.harshit.mentorclasses.mentorClasses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFIUn33YJIrX_nnbJfE9e9rvS02wbD8xU',
    appId: '1:361691330793:web:fa6b7be6436741040bd878',
    messagingSenderId: '361691330793',
    projectId: 'mentor-classes-erp',
    authDomain: 'mentor-classes-erp.firebaseapp.com',
    storageBucket: 'mentor-classes-erp.firebasestorage.app',
    measurementId: 'G-F6NHCCLD6Z',
  );
}
