# Podfile
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Flutter Pod
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(packages_path, '.symlinks', 'plugins', 'flutter_local_notifications', '.dart_tool'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.expand_path(File.join(File.dirname(generated_xcode_build_settings_path), '..', '..', '..', '..'), __FILE__)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter
  load File.join(packages_path, '.symlinks', 'plugins', 'flutter_local_notifications', 'ios', 'flutter_local_notifications.podspec')
  
  # Load all Flutter plugins in pubspec.yaml
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
